# Generated by Django 3.1.7 on 2021-03-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_record_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='year',
        ),
        migrations.AlterField(
            model_name='record',
            name='artist',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
